// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $basemap_index from "./routes/basemap/index.ts";
import * as $cog_index from "./routes/cog/index.ts";
import * as $cog_tilejson_index from "./routes/cog/tilejson/index.ts";
import * as $index from "./routes/index.tsx";
import * as $float_panel from "./islands/float_panel.tsx";
import * as $input from "./islands/input.tsx";
import * as $main from "./islands/main.tsx";
import * as $map from "./islands/map.tsx";
import * as $panels from "./islands/panels.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/basemap/index.ts": $basemap_index,
    "./routes/cog/index.ts": $cog_index,
    "./routes/cog/tilejson/index.ts": $cog_tilejson_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/float_panel.tsx": $float_panel,
    "./islands/input.tsx": $input,
    "./islands/main.tsx": $main,
    "./islands/map.tsx": $map,
    "./islands/panels.tsx": $panels,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
