FROM gcr.io/ramadhan-s4g/eo-base:latest

COPY requirements.txt requirements.txt

RUN python3 -m venv .venv && \
  .venv/bin/pip install -r requirements.txt

COPY . .

RUN gcloud auth login --cred-file=private_key.json
